from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class CitationType(str, Enum):
    """Types of references within the document for citations."""

    METADATA = "metadata"
    RISK_CLAUSE = "risk_clause"
    FEE_TABLE = "fee_table"
    LEGAL_PROVISION = "legal_provision"
    GENERAL = "general"


class ChatCitation(BaseModel):
    """
    Model representing a citation or reference source in a loan document.
    Serves as evidence for AI answers or analytical insights.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "page_number": 8,
                "source_text": "7.2 Prepayment: The Borrower may prepay the outstanding loan amount in whole or part subject to a prepayment fee of 2.0% of the prepaid principal.",
                "confidence": 0.98,
                "citation_type": "legal_provision",
                "clause_reference": "Clause 7.2",
            }
        }
    )

    page_number: int = Field(
        ...,
        ge=1,
        description="The 1-indexed page number of the source document where the text was cited.",
    )

    source_text: str = Field(
        ...,
        description="The exact snippet of text extracted from the document that serves as the basis for the citation.",
        min_length=10,
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="AI confidence score for the citation matching the user query (0.0 to 1.0).",
    )

    citation_type: CitationType = Field(
        ...,
        description="The category of cited content (e.g. risk_clause, fee_table, legal_provision).",
    )

    clause_reference: Optional[str] = Field(
        None,
        description="Optional tag detailing the specific clause number/section title (e.g., 'Clause 7.2').",
    )


class RAGResponse(BaseModel):
    """
    Future-ready model for RAG (Retrieval-Augmented Generation) responses.
    Includes the final AI answer, confidence score, and associated source citations.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "answer": "Yes, you can prepay the loan, but according to Page 8, Clause 7.2, it is subject to a prepayment charge of 2% of the prepaid principal amount.",
                "citations": [
                    {
                        "page_number": 8,
                        "source_text": "7.2 Prepayment: The Borrower may prepay the outstanding loan amount in whole or part subject to a prepayment fee of 2.0% of the prepaid principal.",
                        "confidence": 0.98,
                        "citation_type": "legal_provision",
                        "clause_reference": "Clause 7.2",
                    }
                ],
                "confidence_score": 0.95,
            }
        }
    )

    answer: str = Field(
        ...,
        description="The textual answer generated by the LLM response engine.",
    )

    citations: List[ChatCitation] = Field(
        default_factory=list,
        description="List of document citations and source snippets backing up this answer.",
    )

    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="The cumulative confidence score of the system for both chunk retrieval and answer generation.",
    )

    source_references: List[str] = Field(
        default_factory=list,
        description="List of source file names or page numbers referenced.",
    )

    supporting_clauses: List[str] = Field(
        default_factory=list,
        description="List of contract clauses supporting the answer.",
    )

