from decimal import Decimal
from typing import List
from pydantic import BaseModel, Field, model_validator, ConfigDict
from .loan_metadata import LoanMetadata
from .risk_clause import RiskClause
from .loan_score import LoanSafetyScore


class LoanAnalysisResponse(BaseModel):
    """
    Consolidated analysis response schema for a loan document.
    Powers the Analysis Report Screen, Clause Intelligence Screen, and AI Assistant.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "metadata": {
                    "lender_name": "Apex Finance Corp",
                    "loan_type": "Home Loan",
                    "principal_amount": "5000000.00",
                    "sanctioned_amount": "5000000.00",
                    "interest_rate": 8.75,
                    "interest_type": "floating",
                    "tenure_months": 240,
                    "emi_amount": "44186.00",
                    "processing_fee": "10000.00",
                    "documentation_fee": "2500.00",
                    "insurance_fee": "15000.00",
                    "foreclosure_charges": "2.00",
                    "prepayment_charges": "1.50",
                    "bounce_charges": "500.00",
                    "late_payment_fee": "24.00",
                    "disbursal_amount": "4972500.00",
                    "repayment_frequency": "monthly",
                    "loan_start_date": "2026-06-01",
                    "maturity_date": "2046-06-01",
                },
                "risks": [
                    {
                        "clause_id": "clause_interest_rate_hike",
                        "clause_title": "Unilateral Floating Rate Adjustment",
                        "clause_text": "The Lender reserves the absolute right to modify the margin and/or the Benchmark Rate at any time...",
                        "risk_level": "HIGH",
                        "category": "Interest Rate Risk",
                        "explanation": "Allows the lender to increase interest rates unilaterally...",
                        "page_number": 12,
                        "recommendation": "Negotiate to require at least a 30-day prior written notice...",
                    }
                ],
                "ai_summary": "This is a standard 20-year home loan of $5,000,000 at a floating rate of 8.75%. The agreement features friendly early prepayment options but carries a critical risk of unilateral interest rate updates by the lender.",
                "loan_score": {
                    "score": 7.8,
                    "rating": "Good",
                    "strengths": [
                        "Zero prepayment penalty after 12 months",
                    ],
                    "weaknesses": [
                        "High late payment penalty rate of 24%",
                    ],
                    "explanation": "Transparent structure with average risk exposure.",
                },
                "confidence_score": 0.94,
                "total_interest": "5604640.00",
                "total_payment": "10604640.00",
                "effective_apr": 8.92,
                "recommendations": [
                    "Request waiver of foreclosure charges",
                    "Amend Clause 12.4 to request interest adjustment notifications",
                ],
            }
        }
    )

    metadata: LoanMetadata = Field(
        ...,
        description="The detailed financial and administrative metadata extracted from the loan document.",
    )

    risks: List[RiskClause] = Field(
        default_factory=list,
        description="List of risk clauses identified during document audit.",
    )

    ai_summary: str = Field(
        ...,
        description="Executive summary generated by the AI detailing the key aspects and nature of the loan.",
        min_length=15,
    )

    loan_score: LoanSafetyScore = Field(
        ...,
        description="The safety score assessment detailing loan quality, strengths, and weaknesses.",
    )

    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="The average confidence score of the extraction and risk analysis pipeline (0.0 to 1.0).",
    )

    total_interest: Decimal = Field(
        ...,
        ge=0,
        description="Calculated total interest payable over the entire tenure of the loan.",
    )

    total_payment: Decimal = Field(
        ...,
        ge=0,
        description="Calculated total payment (Principal + Total Interest + Fees) over the entire tenure.",
    )

    effective_apr: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Annual Percentage Rate (APR) reflecting the actual annualized cost of borrowing, including fees.",
    )

    recommendations: List[str] = Field(
        default_factory=list,
        description="Actionable overall negotiation tips and advice for the borrower.",
    )

    @model_validator(mode="after")
    def validate_financial_coherence(self) -> "LoanAnalysisResponse":
        # 1. Total payment must be greater than or equal to principal + interest
        minimum_payment = self.metadata.principal_amount + self.total_interest
        if self.total_payment < minimum_payment:
            raise ValueError(
                f"Total payment ({self.total_payment}) cannot be less than "
                f"Principal + Interest ({minimum_payment})."
            )

        # 2. Total interest must be greater than or equal to 0
        if self.total_interest < 0:
            raise ValueError("Total interest must be greater than or equal to 0.")

        # 3. Effective APR should generally be >= nominal interest rate (fees push it higher).
        # Allow a small buffer for floating point rounding (-0.5%).
        # If the APR looks implausible (calc bug / bad data), correct it to the nominal rate
        # instead of crashing the entire pipeline.
        if self.effective_apr < (self.metadata.interest_rate - 0.5):
            import logging
            logging.getLogger(__name__).warning(
                f"APR ({self.effective_apr}%) is below nominal rate "
                f"({self.metadata.interest_rate}%). Correcting to nominal rate."
            )
            object.__setattr__(self, "effective_apr", round(float(self.metadata.interest_rate), 2))

        return self
